

const activities = [

    "Drink water",
    "Journaling",
    "Dance work out",
    "Zumba",
    "Pilates",
    "Work out with weights",
    "Run on the treadmill",
    "Clean my room",
    "Learn to drive",
    "Book a check up",
    "Practice technical interview questions",
    "Practice interview questions",
    "Learn web design",
    "Design art products",
    "Look for course to go into",
    "Learn about ai",
    "Learn current news about tech",
    "Logic puzzles",
    "Fashion",
    "Look for new fits",
    "Organize closet",
    "Organize current fits",
    "Watch a sweaty tft video",
    "Practice volleyball",
    "Catch up on shows",
    "Make song covers again",
    "Make a mini blog",
    "Duo lingo is watching",
    "MIT Electrical Eng course",
    "Find a dance class in mississauga",
    "Make a game",
    "Make a game clone",
    "Make an app clone",
    "Make a game clone on roblox",
    "Make an app and deploy on app store",
    "Study a random topic",
    "Solo board gaming",
    "Make a list of creative hangouts",
    "Make a mini vlog but on insta",
    "Learn how to play Chess",
    "Take aesthetic Pinterest photos",
    "Make black girl versions of Pinterest art",
    "Recreate a photo from your saved photos vid",
    "Learn animation",
    "Listen to a podcast",
    "Play piano",
    "Learn about robotics",
    "Journal but podcast style",
    "Build a tiny house",
    "Make webtoon art",
    "Make random moments in my day into a webtoon",
    "Watch a spilled ink episode",
    "Work on a New Years resolution",
    "Finish a show that you haven’t finished",
    "Make a pomodoro timer or video with drawings/animations",
    "Work on Spotify playlists",
    "Pick a new screen saver for your devices",
    "Doodle fictional crushes",
    "Make a hear me out",
    "Make stickers",
    "Make gifs",
    "Make a Friendpedia/wiki",
    "Library after work",
    "Make a solo vlog",
    "Take a walk",
    "Learn a kpop dance",
    "Learn to bake",
    "Learn to cook",
    "Make a cosplay",
    "Play picopark or overcooked with the fam",
    "Hangout with family",
    "Hangout with mummy",
    "Encouraging someone with a note or scripture",
    "Write a card to thank someone",
    "Write a card to encourage someone",
    "Pray for others",
    "Hangout with viv and Lauryn after work",
    "Call someone to catch up",
    "Visit grace and sayo on their campus",
    "Write a letter to my friends instead of a text",
    "Make quiz questionnaire websites for frens",
    "Play Stardew valley again"

];

export default activities;